### ISSUE TITLE
Boost Startup Error

### ISSUE THREAD

**Issue by ULucky-22** [pmme/Boost#2]
Hello, 

Upon loading up the Boost command on my server, I received this console error readout and the plugin was disabled.

https://pastebin.com/0nGfejuW

Could you help me fix this issue? I am unsure if I've set something incorrectly or the plugin is incompatible with the new PaperSpigot updates. I think my players would really enjoy this plugin.

Thanks, 
ULucky

**Comment by pmme** [comment]
Hi there ULucky, hopefully we can get this sorted for you quickly.

The problem is connection to the MySQL database. I seriously doubt any Paper update has changed anything relevant.

Do you have MySQL installed, and are you intending to use MySQL for the game statistics database?
Have you configured the port, username and password correctly for your database?
Could you please upload a copy of your config.yml for Boost to pastebin. I suggest to first set the username and password inside to "xxx".

[Edit]
It may be that you've changed your config without realizing what you've set it to do. If you're _not_ planning on using MySQL, you should set "SQLite: true" (the default) which will use a SQLite database for the statistics, which will create a single db file inside the Boost plugin folder. If you choose to use SQLite then the keys under "sql:" are not used. 
Currently there isn't an option to not record game statistics at all.

**Comment by ULucky-22** [comment]
Hello, thanks for this info, the issue has been resolved!

**Comment by pmme** [comment]
Great to hear!
Feel free to get in touch if you have questions about configuration. Probably message on spigot is easiest for that.
Also, since it's now starting you may be concerned that it's taking control of your spawn point etc. If you have multi-world just set the Boost world (the world in which Boost should work) and set an appropriate main lobby spawn point in that world.

**Comment by ULucky-22** [comment]
I am wondering though, is it possible to have Boost disabled for certain worlds? I can't seem to build on my main worlds even when setting the game to it's own separate lobby and arena worlds. It appears when I turn the game off with /boost off, only then can I resume building. I am not using bungeecord, just Multiverse with seperate worlds.

**Comment by pmme** [comment]
Should work fine with multiple worlds.
Have you ensured only the boost world is listed in config.yml in the 'boost_worlds:' setting? If your normal world is called 'world' then make sure that's not listed in 'boost_worlds:'.

**Comment by pmme** [comment]
On any event (e.g. block place, break) if your current world is not listed in 'boost_worlds:' then it leaves the event alone. It only interferes when you're in a world that's listed in the config.yml 'boost_worlds:' setting to protect the lobby and arena builds.

Also, when you're in a boost world you can use '/boost build' and '/boost nobuild' to toggle building for you without affecting other players. So you can build game arenas even while the plugin is running.

**Comment by ULucky-22** [comment]
Thanks, this seems to have fixed it, I had the boostworlds setting unset which is likely why this happened.

**Comment by pmme** [comment]
Yup :)

**Comment by pmme** [comment]
With the boost_worlds setting is empty it assumes it's a dedicated server, a bungeecord server instance entirely dedicated to running Boost.
