### ISSUE TITLE
Can't place TNT with plugin active

### ISSUE THREAD

**Issue by Log1x** [pmme/Boost#6]

**Comment by pmme** [comment]
I think this is just a misunderstanding about how to use the plugin.
Boost actively prevents players from placing _any_ block, not just TNT. Players are not supposed to be able to modify your arena builds.

Your builders or admins can run "/boost build" to put themselves in Boost build mode rather than play mode. To test Boost they would then need to run "/boost nobuild" to switch back to play mode. Players should not have the permission to switch to Boost build mode. Everyone is in play mode by default when they log in. So it is a normal expected procedure that you should run "/boost build" after logging in if you are trying to build your arena.

The other consideration is if you are running a multi-world server (one server with multiple worlds run by MultiVerse or similar) and you have one world provided for Boost and other worlds provided for other games or game modes (e.g. survival, skyblock, etc). In this case you need to tell the Boost plugin which world it should control and which worlds it should ignore. By default, Boost will control all worlds, which is fine if you run a server network with one server and all of its worlds dedicated to Boost. However if, by way of example, your suvival world is the default "world", skyblock is in "world1" and Boost should only run in "world2", you should run the command "/boost addgameworld world2".

If you are still confused, please let me know whether or not you are running a server network or one server, and whether you have one world or multiple worlds, and whether you want to have just Boost or if you want other game modes too. I can then advise specifically what to do based on your desired set-up.

**Comment by Log1x** [comment]
That all makes sense. We've had Boost running on our Minigames server for a bit now – it's in the same world as other games, but we've never had an issue placing blocks until we noticed TNT couldn't be placed in another minigame. Every other block seems to place as intended.

We will move it to another world.
